# 币安交易所三角套利配置
# 配置时间: 2024-01-15
# 策略类型: 三角套利
# 目标利润: 0.15%

[exchange]
name = "binance"
enabled = true
api_key = "aJS2cL8LyIHw5PfUeKvYkdfM1pf0ewaVKI7m0GkwsXs3qYhrVQgHz8mGjkCZ6xL0"
api_secret = "rGrBCqmSxT0khRWFuh72eG6irYw0z82BSvT7cxcIRR1yrxAdJ4jiODnjUkXPLGzk"
sandbox_mode = true  # 使用测试环境
base_url = "https://testnet.binance.vision"
ws_url = "wss://testnet.binance.vision/ws/"

[strategy]
type = "triangular"
enabled = true
min_profit_pct = 0.15  # 最小利润0.15%
max_position_size_usd = 1000.0  # 最大持仓1000 USD（测试用）
max_slippage_pct = 0.05  # 最大滑点5%
execution_timeout_ms = 5000  # 执行超时5秒

[risk_management]
# 风控配置
max_daily_loss_usd = 100.0  # 最大日损失100 USD（测试用）
max_positions = 3  # 最大并发持仓数
stop_loss_pct = 2.0  # 止损2%
max_drawdown_pct = 5.0  # 最大回撤5%

# 币安50个主要币种配置
[symbols]
# 主要交易对 - 支持三角套利的币种组合
major_pairs = [
    # Bitcoin相关
    "BTCUSDT", "BTCETH", "BTCBNB",
    # Ethereum相关
    "ETHUSDT", "ETHBNB", "ETHBTC",
    # Binance Coin相关
    "BNBUSDT", "BNBBTC", "BNBETH",
    # 稳定币相关
    "BUSDUSDT", "USDCUSDT", "TUSDUSDT",
    # 主流币种
    "ADAUSDT", "XRPUSDT", "DOTUSDT", "LINKUSDT", "LTCUSDT",
    "BCHUSDT", "XLMUSDT", "EOSUSDT", "TRXUSDT", "ETCUSDT",
    # DeFi代币
    "UNIUSDT", "AAVEUSDT", "SUSHIUSDT", "COMPUSDT", "MKRUSDT",
    # 其他主流币种
    "SOLUSDT", "AVAXUSDT", "MATICUSDT", "ATOMUSDT", "FILUSDT",
    "VETUSDT", "ICPUSDT", "THETAUSDT", "ALGOUSDT", "NEARUSDT",
    # 新兴币种
    "FTMUSDT", "SANDUSDT", "MANAUSDT", "AXSUSDT", "CHZUSDT",
    # Layer 2 & 扩容解决方案
    "ARBUSDT", "OPUSDT", "LRCUSDT", "ZKSUSDT", "STRKUSDT"
]

# 三角套利路径配置
[triangular_paths]
# 主要三角套利路径
enabled_paths = [
    # BTC三角路径
    ["BTC", "ETH", "USDT"],
    ["BTC", "BNB", "USDT"],
    ["BTC", "ADA", "USDT"],
    # ETH三角路径
    ["ETH", "BNB", "USDT"],
    ["ETH", "LINK", "USDT"],
    ["ETH", "DOT", "USDT"],
    # BNB三角路径
    ["BNB", "ADA", "USDT"],
    ["BNB", "XRP", "USDT"],
    ["BNB", "SOL", "USDT"],
    # 稳定币套利路径
    ["USDT", "BUSD", "BTC"],
    ["USDT", "USDC", "ETH"],
    # DeFi三角路径
    ["UNI", "AAVE", "USDT"],
    ["SUSHI", "COMP", "USDT"],
    # 其他优质路径
    ["SOL", "AVAX", "USDT"],
    ["MATIC", "ATOM", "USDT"],
    ["FIL", "VET", "USDT"],
    ["NEAR", "FTM", "USDT"],
    ["SAND", "MANA", "USDT"],
    ["AXS", "CHZ", "USDT"],
    ["ARB", "OP", "USDT"]
]

[execution]
# 执行配置
concurrent_opportunities = 3  # 并发执行机会数
retry_attempts = 3  # 重试次数
order_type = "MARKET"  # 市价单
time_in_force = "IOC"  # IOC订单（立即成交或取消）

[monitoring]
# 监控配置
log_level = "INFO"
performance_tracking = true
profit_tracking = true
slippage_monitoring = true
latency_monitoring = true

[fees]
# 币安手续费配置
taker_fee = 0.001  # 0.1% taker费率
maker_fee = 0.001  # 0.1% maker费率（测试账户标准费率）