[system]
name = "ArbitrageSystem51"
version = "5.1.0"
environment = "production"
log_level = "info"
max_concurrent_opportunities = 2000
health_check_interval_seconds = 15
metrics_collection_interval_seconds = 3
graceful_shutdown_timeout_seconds = 60
enable_hot_reload = true
enable_telemetry = true
enable_profiling = true
extreme_volatility_threshold = 0.15
caution_volatility_threshold = 0.08
volatility_weight = 1.0
extreme_depth_threshold = 0.3
caution_depth_threshold = 0.5
depth_weight = 1.0
extreme_volume_threshold = 3.0
volume_weight = 1.0
extreme_api_error_threshold = 0.1
api_weight = 1.0
external_event_weight = 1.0
extreme_threshold = 6.0
caution_threshold = 3.0

[monitoring.performance]
enable_performance_monitoring = true
profiling_enabled = true
sampling_rate = 0.05
memory_monitoring = true
cpu_monitoring = true
network_monitoring = true
latency_monitoring = true

[monitoring.performance.data_cleaning.v3_optimization]
memory_pool_size = 262144
vec_pool_capacity = 32768
orderbook_capacity = 4000
zero_alloc_buffer_count = 262144
o1_sort_bucket_count = 524288
entries_per_bucket = 32
enable_intel_optimizations = true
enable_o1_sorting = true
enable_realtime_monitoring = true

[monitoring.performance.data_cleaning.simd_optimization]
batch_size = 2048
enable_avx512 = true
enable_avx2 = true
enable_sse4 = true
auto_detect_simd = true

[monitoring.performance.data_cleaning.memory_management]
max_memory_usage_mb = 2048
enable_zero_allocation = true
enable_pool_preallocation = true
enable_numa_affinity = true

[monitoring.performance.data_cleaning.performance_targets]
target_latency_ns = 25000
max_cpu_usage_percent = 85.0
target_throughput_per_second = 320000

[monitoring.performance.data_cleaning.auto_configuration]
enable_hardware_detection = true
enable_performance_adaptation = true
max_auto_scale_factor = 8.0
scaling_algorithm = "CpuMemoryComposite"

[monitoring.metrics]
enable_metrics = true
metrics_port = 9090
collection_interval_seconds = 5
retention_days = 7

[[exchanges]]
name = "binance"
enabled = true
api_key = "test_key"
api_secret = "test_secret"
api_passphrase = ""
sandbox_mode = true
rate_limit_per_second = 10
websocket_url = "wss://stream.binance.com:9443/ws"
rest_api_url = "https://api.binance.com"
trading_pairs = ["BTC/USDT", "ETH/USDT"]

[strategy]
enabled = true
min_profit_threshold = 0.3
max_position_size = 10000
risk_limit_per_trade = 0.02
max_concurrent_trades = 50

[strategy.inter_exchange]
enabled = true
min_profit_bps = 30
max_latency_ms = 100
slippage_tolerance = 0.1

[strategy.triangular]
enabled = true
min_profit_bps = 25
max_cycles_per_second = 1000
base_currencies = ["BTC", "ETH", "USDT"]

[ai_risk]
enabled = true
risk_model_version = "v2.1"
max_drawdown_percent = 5.0
position_size_limit = 0.1
volatility_threshold = 0.15

[ai_risk.market_conditions]
extreme_volatility_threshold = 0.25
liquidity_threshold = 100000
correlation_threshold = 0.8

[ai_risk.global_limits]
max_daily_loss_usd = 5000.0
max_total_exposure_usd = 100000.0
max_single_position_usd = 10000.0
