[metadata]
version = "1.0.0"
last_updated = "2024-01-15T10:30:00Z"
auto_reload = true
exchange = "bitfinex"

[slippage]
# 基础滑点（基点，万分之一） - Bitfinex专业交易平台，流动性较好
base_slippage = 3
# 最大滑点（基点）
max_slippage = 14
# 交易量影响因子
volume_impact_factor = 0.00001
# 波动率乘数
volatility_multiplier = 1.4
# 市场深度权重 - Bitfinex深度较好
depth_weight = 0.8
# 更新间隔（毫秒）
update_interval_ms = 900

[market_conditions]
# 高波动率阈值
high_volatility_threshold = 0.045
# 低流动性阈值（USD） - Bitfinex机构客户较多，流动性要求高
low_liquidity_threshold = 60000.0
# 紧急滑点（基点）
emergency_slippage = 28
# 紧急情况价差阈值（基点）
emergency_spread_threshold_bps = 420

[optimization]
# 学习率
learning_rate = 0.0012
# 历史数据窗口大小
history_window = 1100
# 最小样本数
min_samples = 130
# 模型重训练间隔（秒）
retrain_interval_seconds = 3300

[validation]
# 最小滑点（基点）
min_slippage = 1
# 最大滑点（基点）
max_slippage = 1000
# 必填字段
required_fields = ["base_slippage", "max_slippage", "volume_impact_factor"]

[[validation.range_checks]]
field = "volatility_multiplier"
min = 1.0
max = 2.5

[[validation.range_checks]]
field = "depth_weight"
min = 0.5
max = 1.0

# Bitfinex特定设置
[exchange_specific]
# VIP等级影响 - Bitfinex专业级费率
vip_discount_factor = 0.85
# 现货vs合约滑点差异
spot_futures_multiplier = 1.05
# 高频交易优化 - Bitfinex支持专业交易
hft_optimization_enabled = true
# Bitfinex特有的保证金交易
margin_trading_multiplier = 1.2
# 借贷市场影响
lending_market_impact = 0.05
# P2P交易特性
p2p_trading_optimization = true
# 专业交易者优化
professional_trader_mode = true