[metadata]
version = "1.0.0"
last_updated = "2024-01-15T10:30:00Z"
auto_reload = true
exchange = "gate"

[slippage]
# 基础滑点（基点，万分之一） - Gate.io流动性中等
base_slippage = 4
# 最大滑点（基点）
max_slippage = 18
# 交易量影响因子
volume_impact_factor = 0.000015
# 波动率乘数
volatility_multiplier = 1.6
# 市场深度权重
depth_weight = 0.7
# 更新间隔（毫秒）
update_interval_ms = 1200

[market_conditions]
# 高波动率阈值
high_volatility_threshold = 0.055
# 低流动性阈值（USD）
low_liquidity_threshold = 40000.0
# 紧急滑点（基点）
emergency_slippage = 35
# 紧急情况价差阈值（基点）
emergency_spread_threshold_bps = 550

[optimization]
# 学习率
learning_rate = 0.0008
# 历史数据窗口大小
history_window = 900
# 最小样本数
min_samples = 120
# 模型重训练间隔（秒）
retrain_interval_seconds = 4200

[validation]
# 最小滑点（基点）
min_slippage = 1.5
# 最大滑点（基点）
max_slippage = 1500
# 必填字段
required_fields = ["base_slippage", "max_slippage", "volume_impact_factor"]

[[validation.range_checks]]
field = "volatility_multiplier"
min = 1.0
max = 3.0

[[validation.range_checks]]
field = "depth_weight"
min = 0.3
max = 0.9

# Gate.io特定设置
[exchange_specific]
# VIP等级影响
vip_discount_factor = 0.92
# 现货vs合约滑点差异
spot_futures_multiplier = 1.15
# 高频交易优化
hft_optimization_enabled = true
# Gate.io特有的GT抵扣手续费机制
gt_deduction_enabled = true
# 点卡系统影响
point_system_multiplier = 0.95
# API限制较严格
rate_limit_compensation_ms = 100