[metadata]
version = "1.0.0"
last_updated = "2024-01-15T10:30:00Z"
auto_reload = true
exchange = "kraken"

[slippage]
# 基础滑点（基点，万分之一） - Kraken老牌交易所，流动性稳定但深度一般
base_slippage = 4
# 最大滑点（基点）
max_slippage = 22
# 交易量影响因子
volume_impact_factor = 0.000018
# 波动率乘数
volatility_multiplier = 1.7
# 市场深度权重
depth_weight = 0.65
# 更新间隔（毫秒） - Kraken API相对较慢
update_interval_ms = 2000

[market_conditions]
# 高波动率阈值
high_volatility_threshold = 0.06
# 低流动性阈值（USD）
low_liquidity_threshold = 35000.0
# 紧急滑点（基点）
emergency_slippage = 45
# 紧急情况价差阈值（基点）
emergency_spread_threshold_bps = 650

[optimization]
# 学习率 - 保守设置适应Kraken的稳定性
learning_rate = 0.0006
# 历史数据窗口大小
history_window = 1500
# 最小样本数
min_samples = 200
# 模型重训练间隔（秒）
retrain_interval_seconds = 5400

[validation]
# 最小滑点（基点）
min_slippage = 2
# 最大滑点（基点）
max_slippage = 3000
# 必填字段
required_fields = ["base_slippage", "max_slippage", "volume_impact_factor"]

[[validation.range_checks]]
field = "volatility_multiplier"
min = 1.2
max = 3.5

[[validation.range_checks]]
field = "depth_weight"
min = 0.2
max = 0.8

# Kraken特定设置
[exchange_specific]
# VIP等级影响 - Kraken的费用等级制度
vip_discount_factor = 0.93
# 现货vs合约滑点差异 - Kraken主要做现货
spot_futures_multiplier = 0.9
# 高频交易优化 - Kraken不太适合高频
hft_optimization_enabled = false
# Kraken特有的稳定币对优化
stablecoin_pair_multiplier = 0.8
# 欧洲时区优化
european_timezone_optimization = true
# API调用限制严格
strict_rate_limit = true