[metadata]
version = "1.0.0"
last_updated = "2024-01-15T10:30:00Z"
auto_reload = true
exchange = "kucoin"

[slippage]
# 基础滑点（基点，万分之一） - KuCoin流动性中等偏上
base_slippage = 3
# 最大滑点（基点）
max_slippage = 16
# 交易量影响因子
volume_impact_factor = 0.000012
# 波动率乘数
volatility_multiplier = 1.5
# 市场深度权重
depth_weight = 0.75
# 更新间隔（毫秒）
update_interval_ms = 1000

[market_conditions]
# 高波动率阈值
high_volatility_threshold = 0.05
# 低流动性阈值（USD）
low_liquidity_threshold = 45000.0
# 紧急滑点（基点）
emergency_slippage = 32
# 紧急情况价差阈值（基点）
emergency_spread_threshold_bps = 480

[optimization]
# 学习率
learning_rate = 0.001
# 历史数据窗口大小
history_window = 1000
# 最小样本数
min_samples = 100
# 模型重训练间隔（秒）
retrain_interval_seconds = 3600

[validation]
# 最小滑点（基点）
min_slippage = 1
# 最大滑点（基点）
max_slippage = 1200
# 必填字段
required_fields = ["base_slippage", "max_slippage", "volume_impact_factor"]

[[validation.range_checks]]
field = "volatility_multiplier"
min = 1.0
max = 2.8

[[validation.range_checks]]
field = "depth_weight"
min = 0.4
max = 1.0

# KuCoin特定设置
[exchange_specific]
# VIP等级影响 - KuCoin VIP体系完善
vip_discount_factor = 0.88
# 现货vs合约滑点差异
spot_futures_multiplier = 1.1
# 高频交易优化
hft_optimization_enabled = true
# KCS抵扣手续费机制
kcs_deduction_enabled = true
# KuCoin特有的做市商计划
market_maker_rebate = true
# 交易挖矿机制影响
trading_mining_multiplier = 0.98