[package]
name = "test-api-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_api_server"
path = "test_api_server.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
