[package]
name = "unified_config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
num_cpus = "1.0"

[lib]
name = "unified_config"
path = "src/lib.rs"