要在独立策略文件夹外新建一个名为“jiagou”的文件夹，并将“高频套利系统5.1++生产级框架 - 完整实现”的架构保存到该文件夹，可以按照以下步骤进行：

1. **创建文件夹**：
   - 在你的计算机上，找到你希望创建“jiagou”文件夹的位置。
   - 右键点击空白处，选择“新建” -> “文件夹”，然后将其命名为“jiagou”。

2. **保存架构**：
   - 找到“高频套利系统5.1++生产级框架 - 完整实现”的相关文件或文档。
   - 将这些文件复制或移动到刚刚创建的“jiagou”文件夹中。

3. **组织模块**：
   - 在“jiagou”文件夹内，可以根据需要进一步创建子文件夹，以便将不同的模块进行分类和组织。

4. **文档记录**：
   - 如果有必要，可以在“jiagou”文件夹内创建一个README文件，记录各个模块的功能和集成方式，以便未来的开发和维护。

完成以上步骤后，你就可以在“jiagou”文件夹中管理和集成各个模块了。