# 注意：这个文件是模板，实际的凭证将通过GitHub Actions动态创建
# 这个文件仅用于文档目的，实际部署时会被覆盖

# GitHub Actions中的动态创建命令：
# kubectl create secret docker-registry docker-hub-secret \
#   --docker-server=docker.io \
#   --docker-username="${{ secrets.DOCKER_USERNAME }}" \
#   --docker-password="${{ secrets.DOCKER_TOKEN }}" \
#   --docker-email="${{ secrets.DOCKER_EMAIL }}" \
#   --namespace=qingxi-market-data \
#   --dry-run=client -o yaml | kubectl apply -f -

apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: qingxi-market-data
type: kubernetes.io/dockerconfigjson
data:
  # 这将由GitHub Actions动态生成
  .dockerconfigjson: ""
