apiVersion: v1
kind: Service
metadata:
  name: qingxi-api-service
  namespace: qingxi-market-data
  labels:
    app.kubernetes.io/name: qingxi-market-data
    app.kubernetes.io/component: api
spec:
  type: LoadBalancer # 如果需要在集群外部访问，使用 LoadBalancer
                     # 如果只在集群内部访问，使用 ClusterIP
  selector:
    app: qingxi-market-data-app # 指向我们的 Deployment 的 Pods
  ports:
    - name: grpc-api
      protocol: TCP
      port: 50051 # Service 端口
      targetPort: 50051 # 容器端口
    - name: metrics
      protocol: TCP
      port: 9091 # Service 端口
      targetPort: 9091 # 容器端口
