apiVersion: v1
kind: Secret
metadata:
  name: qingxi-secrets
  namespace: qingxi-market-data
  labels:
    app.kubernetes.io/name: qingxi-market-data
    app.kubernetes.io/component: security
type: Opaque
stringData:
  # 你可以在这里添加交易所的 API Key/Secret
  # 这些值在CI/CD流水线中会从 GitHub Secrets 注入
  # 例如：
  # BINANCE_API_KEY: "dummy_binance_api_key"
  # BINANCE_SECRET_KEY: "dummy_binance_secret_key"
