# 告警聚合系统配置文件
# Alert Aggregation System Configuration

[general]
# 最大活跃告警数量
max_active_alerts = 10000

# 告警TTL（秒）
alert_ttl_seconds = 3600

# 聚合处理间隔（秒）
aggregation_interval_seconds = 30

# 是否启用根因分析
enable_root_cause_analysis = true

# 是否启用智能抑制
enable_smart_suppression = true

# 默认相似度阈值
default_similarity_threshold = 0.8

# 审计配置
[audit]
# 最大记录数
max_records = 100000

# 记录保留天数
retention_days = 90

# 启用实时同步
enable_real_time_sync = true

# 审计日志文件路径
audit_log_path = "./logs/audit.log"

# 缓冲区大小
buffer_size = 1000

# 启用加密
encryption_enabled = true

# 相似度分析配置
[similarity]
# 编辑距离权重
edit_distance_weight = 0.3

# 余弦相似度权重
cosine_similarity_weight = 0.3

# Jaccard相似度权重
jaccard_similarity_weight = 0.2

# 语义相似度权重
semantic_similarity_weight = 0.2

# 最小文本长度阈值
min_text_length = 5

# 结构相似度配置
[similarity.structural]
# 标签匹配权重
label_match_weight = 0.4

# 指标相似度权重
metric_similarity_weight = 0.3

# 时间相似度权重
temporal_similarity_weight = 0.1

# 来源相似度权重
source_similarity_weight = 0.2

# 默认聚合规则配置
[[rules]]
id = "api_errors"
name = "API Error Aggregation"
window_seconds = 300
max_count = 10
action = "AggregateAndAlert"
enabled = true

  [[rules.conditions]]
  field = "source"
  operator = "Contains"
  value = "api"

  [[rules.conditions]]
  field = "title"
  operator = "Similar"
  value = "error"
  similarity_threshold = 0.8

[[rules]]
id = "database_issues"
name = "Database Issue Correlation"
window_seconds = 600
max_count = 5
action = "AggregateAndEscalate"
enabled = true

  [[rules.conditions]]
  field = "labels.component"
  operator = "Equal"
  value = "database"

  [[rules.conditions]]
  field = "severity"
  operator = "GreaterThan"
  value = "Medium"

[[rules]]
id = "network_timeouts"
name = "Network Timeout Pattern"
window_seconds = 180
max_count = 8
action = "AggregateAndAlert"
enabled = true

  [[rules.conditions]]
  field = "title"
  operator = "Contains"
  value = "timeout"

  [[rules.conditions]]
  field = "labels.type"
  operator = "Equal"
  value = "network"

[[rules]]
id = "high_frequency_noise"
name = "High Frequency Noise Suppression"
window_seconds = 120
max_count = 15
action = "AggregateAndSuppress"
enabled = true

  [[rules.conditions]]
  field = "severity"
  operator = "Equal"
  value = "Low"

[[rules]]
id = "memory_alerts"
name = "Memory Resource Alerts"
window_seconds = 300
max_count = 3
action = "AggregateAndEscalate"
enabled = true

  [[rules.conditions]]
  field = "labels.resource"
  operator = "Equal"
  value = "memory"

  [[rules.conditions]]
  field = "metrics.usage_percent"
  operator = "GreaterThan"
  value = 80

# 抑制规则配置
[[suppression_rules]]
id = "low_severity_flood"
name = "Low Severity Flood Protection"
enabled = true
duration_minutes = 30
reason = "Low severity alert flood suppression"

  [[suppression_rules.conditions]]
  type = "SeverityLevel"
  value = "Low"

  [[suppression_rules.conditions]]
  type = "FrequencyThreshold"
  count = 5
  minutes = 10

[[suppression_rules]]
id = "info_noise_reduction"
name = "Info Alert Noise Reduction"
enabled = true
duration_minutes = 60
reason = "Information alert noise reduction"

  [[suppression_rules.conditions]]
  type = "SeverityLevel"
  value = "Info"

  [[suppression_rules.conditions]]
  type = "FrequencyThreshold"
  count = 10
  minutes = 5

[[suppression_rules]]
id = "test_environment"
name = "Test Environment Alert Suppression"
enabled = true
duration_minutes = 120
reason = "Test environment alerts auto-suppressed"

  [[suppression_rules.conditions]]
  type = "SourcePattern"
  value = "test"

  [[suppression_rules.conditions]]
  type = "SeverityLevel"
  value = "Medium"

[[suppression_rules]]
id = "maintenance_window"
name = "Maintenance Window Suppression"
enabled = false
duration_minutes = 240
reason = "Suppressed during maintenance window"

  [[suppression_rules.conditions]]
  type = "TimeWindow"
  start_hour = 2
  end_hour = 6

  [[suppression_rules.conditions]]
  type = "SeverityLevel"
  value = "Low"

# 根因分析配置
[root_cause]
# 最大历史数据保留
max_history_size = 10000

# 贝叶斯网络置信度阈值
confidence_threshold = 0.7

# 启用机器学习增强
enable_ml_enhancement = true

# 相关性时间窗口（秒）
correlation_window_seconds = 600

# 专家规则权重
expert_rules_weight = 0.6

# 贝叶斯推理权重
bayesian_weight = 0.4

# 通知渠道配置
[[notification_channels]]
type = "Email"
name = "Operations Team"
enabled = true
recipients = ["ops-team@company.com", "alerts@company.com"]

  [notification_channels.config]
  smtp_server = "smtp.company.com"
  smtp_port = 587
  use_tls = true

[[notification_channels]]
type = "Slack"
name = "Alert Channel"
enabled = true

  [notification_channels.config]
  webhook_url = "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  channel = "#alerts"
  username = "AlertBot"

[[notification_channels]]
type = "PagerDuty"
name = "On-Call Team"
enabled = true

  [notification_channels.config]
  integration_key = "YOUR_PAGERDUTY_INTEGRATION_KEY"
  severity_mapping = { "Critical" = "critical", "High" = "error", "Medium" = "warning", "Low" = "info" }

[[notification_channels]]
type = "Webhook"
name = "Custom Integration"
enabled = false

  [notification_channels.config]
  url = "https://your-webhook-endpoint.com/alerts"
  method = "POST"
  headers = { "Authorization" = "Bearer YOUR_TOKEN", "Content-Type" = "application/json" }

# 性能调优配置
[performance]
# 聚合处理器线程数
aggregation_threads = 4

# 相似度计算并行度
similarity_parallelism = 8

# 缓存大小（聚合结果）
aggregation_cache_size = 5000

# 缓存TTL（秒）
cache_ttl_seconds = 1800

# 启用异步处理
enable_async_processing = true

# 批处理大小
batch_size = 100

# 队列大小限制
queue_size_limit = 10000

# 健康检查配置
[health_check]
# 检查间隔（秒）
check_interval_seconds = 30

# 超时时间（秒）
timeout_seconds = 10

# 失败阈值
failure_threshold = 3

# 恢复阈值
recovery_threshold = 2

# 检查项目
enabled_checks = [
    "database_connectivity",
    "queue_health",
    "memory_usage",
    "processing_latency",
    "error_rate"
]

# 告警疲劳度配置
[fatigue_detection]
# 启用疲劳检测
enabled = true

# 疲劳阈值（相同告警频率）
fatigue_threshold = 10

# 检测时间窗口（分钟）
detection_window_minutes = 60

# 自动抑制时长（分钟）
auto_suppression_minutes = 30

# 疲劳衰减因子
decay_factor = 0.8

# 机器学习配置（实验性）
[machine_learning]
# 启用ML功能
enabled = false

# 模型类型
model_type = "RandomForest"

# 训练数据窗口（天）
training_window_days = 30

# 模型更新间隔（小时）
model_update_interval_hours = 24

# 特征工程配置
feature_extraction = [
    "text_similarity",
    "temporal_patterns", 
    "source_correlation",
    "severity_distribution",
    "label_clustering"
]

# 预测置信度阈值
prediction_confidence_threshold = 0.75

# 集成配置
[integrations]
# Prometheus指标导出
prometheus_enabled = true
prometheus_port = 9090

# Grafana仪表板
grafana_enabled = true
grafana_dashboard_path = "./dashboards/alert_aggregation.json"

# OpenTelemetry追踪
opentelemetry_enabled = true
opentelemetry_endpoint = "http://localhost:4317"

# 日志配置
[logging]
# 日志级别
level = "INFO"

# 日志格式
format = "json"

# 日志文件路径
file_path = "./logs/alert_aggregation.log"

# 日志轮转
rotation_enabled = true
max_file_size = "100MB"
max_files = 10

# 结构化日志字段
structured_logging = true
include_trace_id = true
include_span_id = true